//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementORG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVisit
    {
        public int Id { get; set; }
        public Nullable<int> DoctId { get; set; }
        public Nullable<int> PatientId { get; set; }
        public string Complaint { get; set; }
        public Nullable<System.DateTime> DateOfVisit { get; set; }
    
        public virtual tblDoctor tblDoctor { get; set; }
        public virtual tblPatient tblPatient { get; set; }
    }
}
